# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download

builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  main: ./cmd/lsec2/main.go
  flags:
    - -a
    - -tags
    - netgo
    - -installsuffix
    - netgo
  ldflags:
    - -w
    - -s
    - -extldflags "-static"
    - -X github.com/goldeneggg/lsec2/cmd/lsec2/cli.BuildDate={{.Date}}
    - -X github.com/goldeneggg/lsec2/cmd/lsec2/cli.BuildCommit={{.ShortCommit}}
    - -X github.com/goldeneggg/lsec2/cmd/lsec2/cli.GoVersion={{.Env.GOVERSION}}
  goos:
    - linux
    - freebsd
    - darwin
    - windows
  goarch:
    - amd64
    - 386
  ignore:
    - goos: darwin
      goarch: 386
    - goos: windows
      goarch: 386

archives:
-
  format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brews:
-
  github:
    owner: goldeneggg
    name: homebrew-tap
  commit_author:
    name: Fuminori Sakamoto
    email: jpshadowapps@gmail.com
  folder: Formula
  homepage: 'https://github.com/goldeneggg/lsec2'
  description: 'List view of aws ec2 instances'
  test: |
    system '#{bin}/lsec2 -v'

# Note:
# "brew install rpm" is required on OS X
nfpms:
-
  license: MIT
  maintainer: Fuminori Sakamoto
  homepage: https://github.com/goldeneggg/lsec2
  formats:
    - deb
    - rpm
