language: go

go:
  - 1.11.x
  - 1.12.x
  - master

matrix:
  allow_failures:
    - go: master

addons:
  apt:
    packages:
      - rpm

sudo: false

env:
  - GO111MODULE=on

install:
  - echo $TRAVIS_GO_VERSION
  - go mod download

script:
  - make ci-test

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux && $TRAVIS_GO_VERSION =~ ^1\.12.*

notifications:
  email:
    on_success: never
